"""add_low_stock_threshold_to_products

Revision ID: 8d1d60b9710b
Revises: 39350b3c6e6f
Create Date: 2026-06-09 17:25:38.570119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1d60b9710b'
down_revision: Union[str, Sequence[str], None] = '39350b3c6e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=False))
    op.alter_column('products', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('products', 'gst_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'gst_rate',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_column('products', 'low_stock_threshold')
    # ### end Alembic commands ###
